### ISSUE TITLE
Faker vs Church?

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/elizabeth#12]
[A small comparison](https://github.com/lk-geimfari/church/blob/master/examples/faker_vs_church.py)

P.S If you think that I'm not objective, then you can double-check result. I'll be glad to know the weaknesses of `church`.

**Comment by vltr** [comment]
py2 + faker is still a major plus, at least for me :wink:

**Comment by lk-geimfari** [comment]
@vltr We refused from Python 2, because we use `lru_cache`.

**Comment by vltr** [comment]
Np. Don't take this seriously, I was mostly kidding because it would be (in
math terms) impossible to measure this bench in py2 ;)

Nevertheless, I was curious about why not having a py2 version, and you
answer it :)

Cheers!
Richard.

Em 5 de out de 2016 5:56 AM, "Lk Geimfari" <notifications@github.com>
escreveu:

**Comment by lk-geimfari** [comment]
@vltr Oh, okay. Thank you for your interest!

**Comment by ulgens** [comment]
@lk-geimfari Why did you delete the comparison? Does any copy of it still exist?

**Comment by lk-geimfari** [comment]
@ulgens You can find very small comparison [here](https://gist.github.com/lk-geimfari/461ce92fd32379d7b73c9e12164a9154).

Result:

![alt](https://hsto.org/getpro/habr/comment_images/f2f/77a/ed2/f2f77aed2867c4c6ab8cdc6a5db6a77e.png)

**Comment by ulgens** [comment]
Oh, thank you.

**Comment by lk-geimfari** [comment]
@ulgens You're welcome!
