### ISSUE TITLE
Question: Subclassing a locale

### ISSUE THREAD

**Issue by jrast** [lk-geimfari/elizabeth#150]
I thought about creating a `de-ch` locale. And, as `de-ch` is just a special version of `de`, it would be nice to subclass the `de` locale and replace only the needed fields instead of copy the whole data and maintain a separate data set. Is this possible?

**Comment by lk-geimfari** [comment]
@jrast I also thought about this, but at the moment we have to duplicate some data for similar locales. I think that it's possible, but we need to develop special mechanism for it. It's also would be helpful for `en-*`. If you have any idea we can try do it.

@wikkiewikkie Look, please.

**Comment by wikkiewikkie** [comment]
@lk-geimfari   I am in favor of this.  It not only reduces the amount of data to maintain, but makes it clearer what the differences are between related locales.

It will slow down initial loading of locale data as it would be reading two files instead of one, and also updating the dict, but keep in mind those calls are memoized using lru_cache.

I can put together a PR for the feature.

**Comment by lk-geimfari** [comment]
@wikkiewikkie Okay. I think that the speed loss will be insignificant. Thanks.

**Comment by lk-geimfari** [comment]
@jrast Hi! Sub-locales has been implemented (thanks for @wikkiewikkie). Feel free to add `de-ch`. Thank you!

**Comment by lk-geimfari** [comment]
@jrast I just [added](https://github.com/lk-geimfari/elizabeth/commit/9c546965e5fa50f621487ecdb4ef1019939653a7) `de-ch`. Please, check correctness of data and update it, if you can. Unfortunately I find it difficult to find information in German. Thanks you.

**Comment by jrast** [comment]
Thanks! Just had time to have a quick look at it and it seems to work. However, I had no time to look (and update) the data.
